name: Test Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  fork:
  workflow_dispatch:

jobs:
  run-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "Repository Checkout"
      - uses: ./.github/workflows/setup-uv-env
        name: "Setup UV environment"
        with:
          python-version: "3.11"
          install-ci-dependencies: "true"
          install-dev-dependencies: "false"
      - name: run coverage
        run: |
          uv run coverage run -m pytest
          uv run coverage report --fail-under=95