name: Code Format

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]
  fork:
  workflow_dispatch:

jobs:
  run-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-poetry-env
        with:
          python-version: "3.11"
      - name: run black
        run: |
          black -l 120 --check .